management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

spring:
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true

spring.sleuth.sampler.probability: 1.0

eureka:
  instance:
    preferIpAddress=true:

management.endpoint.health.show-details: always